name: Update Readme

on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '40 * * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          stable: 'true'
          go-version: '1.14.4'

      - name: build
        run: |
          go build -o gen_readme .
          gen_readme
