name: Update Readme

on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '0 */4 * * *'

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@master
      
      - name: setup go
        uses: actions/setup-go@v2
        with:
          stable: 'true'
          go-version: '1.14.4'
      
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Kolkata
      
      - name: build
        env:
          WEATHER_KEY: ${{ secrets.WEATHER_KEY }}
        run: go run main.go weather.go
      
      - name: Commit results
        run: |
          git config --global user.email "readme-bot@example.com"
          git config --global user.name "README-bot"
          git add .
          git commit -m "Update readme" -a || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
